CREATE TABLE Items (ItemID SERIAL PRIMARY KEY, name TEXT, quantity INTEGER, visible INTEGER);

CREATE TABLE ArrivedItems (ArrivedID SERIAL PRIMARY KEY, ItemID INTEGER REFERENCES Items, quantity INTEGER, visible INTEGER);

CREATE TABLE Customer (CustomerID SERIAL PRIMARY KEY, name TEXT, visible INTEGER);

CREATE TABLE CustomerOrder (CustomerOrderID SERIAL PRIMARY KEY, CustomerID INTEGER REFERENCES Customer, ItemID INTEGER REFERENCES Items, quantity INTEGER, visible INTEGER);